---
fabric_name: OM_FABRIC

underlay_routing_protocol: ebgp

overlay_routing_protocol: ebgp

evpn_vlan_aware_bundles: false

# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  evpn_overlay_peers:
      password: "q+VNViP5i4rVjW1cxFv2wA=="

# BGP defaults
bgp_default_ipv4_unicast: false
bgp_update_wait_install: false
bgp_update_wait_for_convergence: false
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200

spine:
  defaults:
    platform: cEOS-LAB
    bgp_as: '65001'
    loopback_ipv4_pool: 192.168.255.0/24
  nodes:
    - name: om-spine1
      id: 1
      mgmt_ip: 172.144.100.2/24
    - name: om-spine2
      id: 2
      mgmt_ip: 172.144.100.3/24

l3leaf:
  defaults:
    platform: cEOS-LAB
    uplink_switches:
      - om-spine1
      - om-spine2
    uplink_interfaces:
      - Ethernet1
      - Ethernet2
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    evpn_services_l2_only: true
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_ipv4_pool: 172.31.255.0/24
  node_groups:
    - group: POD_1
      mlag: false
      nodes:
        - name: om-pe11
          id: 1
          bgp_as: '65101'
          mgmt_ip: 172.144.100.4/24
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet1
        - name: om-pe12
          id: 2
          bgp_as: '65102'
          mgmt_ip: 172.144.100.5/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2
    - group: POD_2
      mlag: false
      nodes:
        - name: om-pe21
          id: 3
          bgp_as: '65103'
          mgmt_ip: 172.144.100.6/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
        - name: om-pe22
          id: 4
          bgp_as: '65104'
          mgmt_ip: 172.144.100.7/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4

# Enable Route Target Membership Constraint Address Family on EVPN overlay BGP peerings
evpn_overlay_bgp_rtc: true
