username: admin
password: admin
port: 6030
timeout: 10s
skip-verify: true
encoding: json_ietf
#debug: true

targets:
  om-spine1:
    insecure: true
  om-spine2:
    insecure: true
  om-pe11:
    insecure: true
  om-pe12:
    insecure: true
  om-pe21:
    insecure: true
  om-pe22:
    insecure: true
subscriptions:
  bgp_neighbors:
    paths:
      - /network-instances/network-instance[name=default]/protocols/protocol[name=BGP]/bgp/neighbors
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  cpu:
    paths:
      - components/component/cpu
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  cpu_load_avg:
    paths:
      - eos_native:/Kernel/sysinfo
    mode: stream
    stream-mode: sample
    sample-interval: 5s


  memory:
    paths:
      - components/component/state/memory/
      - system/memory/kernel/state
      - system/memory/state

    mode: stream
    stream-mode: sample
    sample-interval: 5s

  intf_ctrs:
    paths:
      - /interfaces/interface[name=*]/state/counters
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  intf_admin_state:
    paths:
      - /interfaces/interface[name=*]/state/admin-status
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  intf_oper_state:
    paths:
      - /interfaces/interface[name=*]/state/oper-status
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  intf_config:
    paths:
      - interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/config
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  show_ver:
    paths:
    - eos_native:/Eos/image
    mode: stream
    stream-mode: sample
    sample-interval: 60s

  boot_time:
    paths:
    - system/state/boot-time
    mode: stream
    stream-mode: sample
    sample-interval: 60s

  hardware:
    paths:
    - components/component/state
    - eos_native:/Sysdb/hardware/entmib
    mode: stream
    stream-mode: sample
    sample-interval: 60s

outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    strings-as-labels: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - bounce-map
      - eos-version
      # - tag-status
      #- set-timestamp-processor
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  eos-version:
    event-strings:
      value-names:
        - ".*version$"
        - ".*arch$"
      transforms:
        - replace:
            apply-on: "value"
            old: "EOS"
            new: "eos"
    # event-to-tag:
    #   value-names:
    #     - ".*version$"
    #     - ".*arch$"
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  bounce-map:
    event-strings:
      value-names:
        - oper-status
        - admin-status
      transforms:
        - replace:
            apply-on: "value"
            old: "UP"
            new: "1"
        - replace:
            apply-on: "value"
            old: "DOWN"
            new: "0"
