- name: Build cEOS EVPN VXLAN All-active Multi-homing IRB Fabric (eBGP Overlay and eBGP Underlay)
  hosts: OM_FABRIC
  tasks:
    # - name: Generate EOS configuration Snapshots
    #   tags: [snapshot]
    #   import_role:
    #     name: arista.avd.eos_snapshot

    - name: Generate AVD Structured Configurations and Fabric Documentation
      import_role:
        name: arista.avd.eos_designs

    - name: Generate Switch Intended Configurations and Documentation
      import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Deploy generated configuration to devices
      tags: [deploy]
      import_role:
        name: arista.avd.eos_config_deploy_eapi

    # - name: Validate states on EOS devices
    #   tags: [verify, never]
    #   import_role:
    #     name: arista.avd.eos_validate_state
