name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '39 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 180
        days-before-issue-close: 14
        stale-issue-message: 'This issue has been marked stale given 180 days of inactivity.  It will be automatically
          closed in 14 days if there are no updates.'
        stale-issue-label: 'no-issue-activity'
        days-before-pr-close: 14
        stale-pr-message: 'This pull request has been marked stale given 60 days of inactivity.  It will be automatically
          closed in 14 days if there are no updates.'
        stale-pr-label: 'no-pr-activity'
